package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cake generated by hbm2java
 */
public class Cake  implements java.io.Serializable {


     private Integer idcake;
     private Seller seller;
     private UserRegistration userRegistration;
     private String name;
     private int type;
     private String size;
     private String weight;
     private String imgurl1;
     private String imgurl2;
     private String imgurl3;
     private String colour;
     private Set categoryHasCakes = new HashSet(0);
     private Set cakestores = new HashSet(0);

    public Cake() {
    }

	
    public Cake(Seller seller, UserRegistration userRegistration, int type) {
        this.seller = seller;
        this.userRegistration = userRegistration;
        this.type = type;
    }
    public Cake(Seller seller, UserRegistration userRegistration, String name, int type, String size, String weight, String imgurl1, String imgurl2, String imgurl3, String colour, Set categoryHasCakes, Set cakestores) {
       this.seller = seller;
       this.userRegistration = userRegistration;
       this.name = name;
       this.type = type;
       this.size = size;
       this.weight = weight;
       this.imgurl1 = imgurl1;
       this.imgurl2 = imgurl2;
       this.imgurl3 = imgurl3;
       this.colour = colour;
       this.categoryHasCakes = categoryHasCakes;
       this.cakestores = cakestores;
    }
   
    public Integer getIdcake() {
        return this.idcake;
    }
    
    public void setIdcake(Integer idcake) {
        this.idcake = idcake;
    }
    public Seller getSeller() {
        return this.seller;
    }
    
    public void setSeller(Seller seller) {
        this.seller = seller;
    }
    public UserRegistration getUserRegistration() {
        return this.userRegistration;
    }
    
    public void setUserRegistration(UserRegistration userRegistration) {
        this.userRegistration = userRegistration;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    public String getImgurl1() {
        return this.imgurl1;
    }
    
    public void setImgurl1(String imgurl1) {
        this.imgurl1 = imgurl1;
    }
    public String getImgurl2() {
        return this.imgurl2;
    }
    
    public void setImgurl2(String imgurl2) {
        this.imgurl2 = imgurl2;
    }
    public String getImgurl3() {
        return this.imgurl3;
    }
    
    public void setImgurl3(String imgurl3) {
        this.imgurl3 = imgurl3;
    }
    public String getColour() {
        return this.colour;
    }
    
    public void setColour(String colour) {
        this.colour = colour;
    }
    public Set getCategoryHasCakes() {
        return this.categoryHasCakes;
    }
    
    public void setCategoryHasCakes(Set categoryHasCakes) {
        this.categoryHasCakes = categoryHasCakes;
    }
    public Set getCakestores() {
        return this.cakestores;
    }
    
    public void setCakestores(Set cakestores) {
        this.cakestores = cakestores;
    }




}


