package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cakestore generated by hbm2java
 */
public class Cakestore  implements java.io.Serializable {


     private Integer idcakestore;
     private Cake cake;
     private Integer qty;
     private Double unitPrice;
     private Set cakeUploads = new HashSet(0);
     private Set invoiceItems = new HashSet(0);
     private Set cartItems = new HashSet(0);

    public Cakestore() {
    }

	
    public Cakestore(Cake cake) {
        this.cake = cake;
    }
    public Cakestore(Cake cake, Integer qty, Double unitPrice, Set cakeUploads, Set invoiceItems, Set cartItems) {
       this.cake = cake;
       this.qty = qty;
       this.unitPrice = unitPrice;
       this.cakeUploads = cakeUploads;
       this.invoiceItems = invoiceItems;
       this.cartItems = cartItems;
    }
   
    public Integer getIdcakestore() {
        return this.idcakestore;
    }
    
    public void setIdcakestore(Integer idcakestore) {
        this.idcakestore = idcakestore;
    }
    public Cake getCake() {
        return this.cake;
    }
    
    public void setCake(Cake cake) {
        this.cake = cake;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Set getCakeUploads() {
        return this.cakeUploads;
    }
    
    public void setCakeUploads(Set cakeUploads) {
        this.cakeUploads = cakeUploads;
    }
    public Set getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set invoiceItems) {
        this.invoiceItems = invoiceItems;
    }
    public Set getCartItems() {
        return this.cartItems;
    }
    
    public void setCartItems(Set cartItems) {
        this.cartItems = cartItems;
    }




}


