package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0



/**
 * CartItem generated by hbm2java
 */
public class CartItem  implements java.io.Serializable {


     private Integer idcardItem;
     private Cakestore cakestore;
     private Cart cart;
     private Double unitPrice;
     private Integer qty;
     private Double discount;
     private Double total;

    public CartItem() {
    }

	
    public CartItem(Cakestore cakestore, Cart cart) {
        this.cakestore = cakestore;
        this.cart = cart;
    }
    public CartItem(Cakestore cakestore, Cart cart, Double unitPrice, Integer qty, Double discount, Double total) {
       this.cakestore = cakestore;
       this.cart = cart;
       this.unitPrice = unitPrice;
       this.qty = qty;
       this.discount = discount;
       this.total = total;
    }
   
    public Integer getIdcardItem() {
        return this.idcardItem;
    }
    
    public void setIdcardItem(Integer idcardItem) {
        this.idcardItem = idcardItem;
    }
    public Cakestore getCakestore() {
        return this.cakestore;
    }
    
    public void setCakestore(Cakestore cakestore) {
        this.cakestore = cakestore;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


