package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0



/**
 * CategoryHasCake generated by hbm2java
 */
public class CategoryHasCake  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private Cake cake;

    public CategoryHasCake() {
    }

    public CategoryHasCake(Category category, Cake cake) {
       this.category = category;
       this.cake = cake;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Cake getCake() {
        return this.cake;
    }
    
    public void setCake(Cake cake) {
        this.cake = cake;
    }




}


