package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int idcategory;
     private String categoryName;
     private Set categoryHasCakes = new HashSet(0);

    public Category() {
    }

	
    public Category(int idcategory) {
        this.idcategory = idcategory;
    }
    public Category(int idcategory, String categoryName, Set categoryHasCakes) {
       this.idcategory = idcategory;
       this.categoryName = categoryName;
       this.categoryHasCakes = categoryHasCakes;
    }
   
    public int getIdcategory() {
        return this.idcategory;
    }
    
    public void setIdcategory(int idcategory) {
        this.idcategory = idcategory;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set getCategoryHasCakes() {
        return this.categoryHasCakes;
    }
    
    public void setCategoryHasCakes(Set categoryHasCakes) {
        this.categoryHasCakes = categoryHasCakes;
    }




}


