package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable {


     private int idchat;
     private UserRegistration userRegistrationByToUser;
     private UserRegistration userRegistrationByFromUser;
     private String messages;
     private Date date;
     private Date time;
     private String status;

    public Chat() {
    }

	
    public Chat(int idchat, UserRegistration userRegistrationByToUser, UserRegistration userRegistrationByFromUser) {
        this.idchat = idchat;
        this.userRegistrationByToUser = userRegistrationByToUser;
        this.userRegistrationByFromUser = userRegistrationByFromUser;
    }
    public Chat(int idchat, UserRegistration userRegistrationByToUser, UserRegistration userRegistrationByFromUser, String messages, Date date, Date time, String status) {
       this.idchat = idchat;
       this.userRegistrationByToUser = userRegistrationByToUser;
       this.userRegistrationByFromUser = userRegistrationByFromUser;
       this.messages = messages;
       this.date = date;
       this.time = time;
       this.status = status;
    }
   
    public int getIdchat() {
        return this.idchat;
    }
    
    public void setIdchat(int idchat) {
        this.idchat = idchat;
    }
    public UserRegistration getUserRegistrationByToUser() {
        return this.userRegistrationByToUser;
    }
    
    public void setUserRegistrationByToUser(UserRegistration userRegistrationByToUser) {
        this.userRegistrationByToUser = userRegistrationByToUser;
    }
    public UserRegistration getUserRegistrationByFromUser() {
        return this.userRegistrationByFromUser;
    }
    
    public void setUserRegistrationByFromUser(UserRegistration userRegistrationByFromUser) {
        this.userRegistrationByFromUser = userRegistrationByFromUser;
    }
    public String getMessages() {
        return this.messages;
    }
    
    public void setMessages(String messages) {
        this.messages = messages;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


