package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0



/**
 * CostDetail generated by hbm2java
 */
public class CostDetail  implements java.io.Serializable {


     private int idcostDetail;
     private UserRegistration userRegistration;
     private String deliveryDetail;

    public CostDetail() {
    }

	
    public CostDetail(int idcostDetail, UserRegistration userRegistration) {
        this.idcostDetail = idcostDetail;
        this.userRegistration = userRegistration;
    }
    public CostDetail(int idcostDetail, UserRegistration userRegistration, String deliveryDetail) {
       this.idcostDetail = idcostDetail;
       this.userRegistration = userRegistration;
       this.deliveryDetail = deliveryDetail;
    }
   
    public int getIdcostDetail() {
        return this.idcostDetail;
    }
    
    public void setIdcostDetail(int idcostDetail) {
        this.idcostDetail = idcostDetail;
    }
    public UserRegistration getUserRegistration() {
        return this.userRegistration;
    }
    
    public void setUserRegistration(UserRegistration userRegistration) {
        this.userRegistration = userRegistration;
    }
    public String getDeliveryDetail() {
        return this.deliveryDetail;
    }
    
    public void setDeliveryDetail(String deliveryDetail) {
        this.deliveryDetail = deliveryDetail;
    }




}


