package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * DeliveryDetails generated by hbm2java
 */
public class DeliveryDetails  implements java.io.Serializable {


     private Integer iddeliveryDetails;
     private InvoiceItem invoiceItem;
     private String feedback;
     private String revName;
     private String status;
     private Date date;
     private String complain;

    public DeliveryDetails() {
    }

	
    public DeliveryDetails(InvoiceItem invoiceItem) {
        this.invoiceItem = invoiceItem;
    }
    public DeliveryDetails(InvoiceItem invoiceItem, String feedback, String revName, String status, Date date, String complain) {
       this.invoiceItem = invoiceItem;
       this.feedback = feedback;
       this.revName = revName;
       this.status = status;
       this.date = date;
       this.complain = complain;
    }
   
    public Integer getIddeliveryDetails() {
        return this.iddeliveryDetails;
    }
    
    public void setIddeliveryDetails(Integer iddeliveryDetails) {
        this.iddeliveryDetails = iddeliveryDetails;
    }
    public InvoiceItem getInvoiceItem() {
        return this.invoiceItem;
    }
    
    public void setInvoiceItem(InvoiceItem invoiceItem) {
        this.invoiceItem = invoiceItem;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }
    public String getRevName() {
        return this.revName;
    }
    
    public void setRevName(String revName) {
        this.revName = revName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getComplain() {
        return this.complain;
    }
    
    public void setComplain(String complain) {
        this.complain = complain;
    }




}


