package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Interfaces generated by hbm2java
 */
public class Interfaces  implements java.io.Serializable {


     private int idinterfaces;
     private String url;
     private String interfaceName;
     private Set privilageses = new HashSet(0);

    public Interfaces() {
    }

	
    public Interfaces(int idinterfaces) {
        this.idinterfaces = idinterfaces;
    }
    public Interfaces(int idinterfaces, String url, String interfaceName, Set privilageses) {
       this.idinterfaces = idinterfaces;
       this.url = url;
       this.interfaceName = interfaceName;
       this.privilageses = privilageses;
    }
   
    public int getIdinterfaces() {
        return this.idinterfaces;
    }
    
    public void setIdinterfaces(int idinterfaces) {
        this.idinterfaces = idinterfaces;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getInterfaceName() {
        return this.interfaceName;
    }
    
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }
    public Set getPrivilageses() {
        return this.privilageses;
    }
    
    public void setPrivilageses(Set privilageses) {
        this.privilageses = privilageses;
    }




}


