package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * InvoiceItem generated by hbm2java
 */
public class InvoiceItem  implements java.io.Serializable {


     private Integer idinvoiceItem;
     private Cakestore cakestore;
     private Invoice invoice;
     private Integer qty;
     private Set deliveryDetailses = new HashSet(0);

    public InvoiceItem() {
    }

	
    public InvoiceItem(Cakestore cakestore, Invoice invoice) {
        this.cakestore = cakestore;
        this.invoice = invoice;
    }
    public InvoiceItem(Cakestore cakestore, Invoice invoice, Integer qty, Set deliveryDetailses) {
       this.cakestore = cakestore;
       this.invoice = invoice;
       this.qty = qty;
       this.deliveryDetailses = deliveryDetailses;
    }
   
    public Integer getIdinvoiceItem() {
        return this.idinvoiceItem;
    }
    
    public void setIdinvoiceItem(Integer idinvoiceItem) {
        this.idinvoiceItem = idinvoiceItem;
    }
    public Cakestore getCakestore() {
        return this.cakestore;
    }
    
    public void setCakestore(Cakestore cakestore) {
        this.cakestore = cakestore;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Set getDeliveryDetailses() {
        return this.deliveryDetailses;
    }
    
    public void setDeliveryDetailses(Set deliveryDetailses) {
        this.deliveryDetailses = deliveryDetailses;
    }




}


