package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private int idmessages;
     private String name;
     private String email;
     private String message;

    public Messages() {
    }

	
    public Messages(int idmessages) {
        this.idmessages = idmessages;
    }
    public Messages(int idmessages, String name, String email, String message) {
       this.idmessages = idmessages;
       this.name = name;
       this.email = email;
       this.message = message;
    }
   
    public int getIdmessages() {
        return this.idmessages;
    }
    
    public void setIdmessages(int idmessages) {
        this.idmessages = idmessages;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


