package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0



/**
 * Privilages generated by hbm2java
 */
public class Privilages  implements java.io.Serializable {


     private int pid;
     private Interfaces interfaces;
     private UserType userType;

    public Privilages() {
    }

    public Privilages(int pid, Interfaces interfaces, UserType userType) {
       this.pid = pid;
       this.interfaces = interfaces;
       this.userType = userType;
    }
   
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public Interfaces getInterfaces() {
        return this.interfaces;
    }
    
    public void setInterfaces(Interfaces interfaces) {
        this.interfaces = interfaces;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }




}


