package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Seller generated by hbm2java
 */
public class Seller  implements java.io.Serializable {


     private Integer idauthor;
     private String fname;
     private String lname;
     private String no;
     private String street;
     private String city;
     private String email;
     private String mobile;
     private Set cakes = new HashSet(0);

    public Seller() {
    }

    public Seller(String fname, String lname, String no, String street, String city, String email, String mobile, Set cakes) {
       this.fname = fname;
       this.lname = lname;
       this.no = no;
       this.street = street;
       this.city = city;
       this.email = email;
       this.mobile = mobile;
       this.cakes = cakes;
    }
   
    public Integer getIdauthor() {
        return this.idauthor;
    }
    
    public void setIdauthor(Integer idauthor) {
        this.idauthor = idauthor;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public Set getCakes() {
        return this.cakes;
    }
    
    public void setCakes(Set cakes) {
        this.cakes = cakes;
    }




}


