package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserRegistration generated by hbm2java
 */
public class UserRegistration  implements java.io.Serializable {


     private Integer uid;
     private UserType userType;
     private String fname;
     private String lname;
     private String mobile;
     private String email;
     private String registerDate;
     private String password;
     private String imgUrl;
     private String status;
     private String rate;
     private Set carts = new HashSet(0);
     private Set chatsForFromUser = new HashSet(0);
     private Set chatsForToUser = new HashSet(0);
     private Set cakes = new HashSet(0);
     private Set cakeUploads = new HashSet(0);
     private Set userLogins = new HashSet(0);
     private Set costDetails = new HashSet(0);
     private Set userAddresses = new HashSet(0);
     private Set invoices = new HashSet(0);

    public UserRegistration() {
    }

	
    public UserRegistration(UserType userType) {
        this.userType = userType;
    }
    public UserRegistration(UserType userType, String fname, String lname, String mobile, String email, String registerDate, String password, String imgUrl, String status, String rate, Set carts, Set chatsForFromUser, Set chatsForToUser, Set cakes, Set cakeUploads, Set userLogins, Set costDetails, Set userAddresses, Set invoices) {
       this.userType = userType;
       this.fname = fname;
       this.lname = lname;
       this.mobile = mobile;
       this.email = email;
       this.registerDate = registerDate;
       this.password = password;
       this.imgUrl = imgUrl;
       this.status = status;
       this.rate = rate;
       this.carts = carts;
       this.chatsForFromUser = chatsForFromUser;
       this.chatsForToUser = chatsForToUser;
       this.cakes = cakes;
       this.cakeUploads = cakeUploads;
       this.userLogins = userLogins;
       this.costDetails = costDetails;
       this.userAddresses = userAddresses;
       this.invoices = invoices;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(String registerDate) {
        this.registerDate = registerDate;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getImgUrl() {
        return this.imgUrl;
    }
    
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getRate() {
        return this.rate;
    }
    
    public void setRate(String rate) {
        this.rate = rate;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getChatsForFromUser() {
        return this.chatsForFromUser;
    }
    
    public void setChatsForFromUser(Set chatsForFromUser) {
        this.chatsForFromUser = chatsForFromUser;
    }
    public Set getChatsForToUser() {
        return this.chatsForToUser;
    }
    
    public void setChatsForToUser(Set chatsForToUser) {
        this.chatsForToUser = chatsForToUser;
    }
    public Set getCakes() {
        return this.cakes;
    }
    
    public void setCakes(Set cakes) {
        this.cakes = cakes;
    }
    public Set getCakeUploads() {
        return this.cakeUploads;
    }
    
    public void setCakeUploads(Set cakeUploads) {
        this.cakeUploads = cakeUploads;
    }
    public Set getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set userLogins) {
        this.userLogins = userLogins;
    }
    public Set getCostDetails() {
        return this.costDetails;
    }
    
    public void setCostDetails(Set costDetails) {
        this.costDetails = costDetails;
    }
    public Set getUserAddresses() {
        return this.userAddresses;
    }
    
    public void setUserAddresses(Set userAddresses) {
        this.userAddresses = userAddresses;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


