package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer iduserType;
     private String userType;
     private Set userRegistrations = new HashSet(0);
     private Set privilageses = new HashSet(0);

    public UserType() {
    }

    public UserType(String userType, Set userRegistrations, Set privilageses) {
       this.userType = userType;
       this.userRegistrations = userRegistrations;
       this.privilageses = privilageses;
    }
   
    public Integer getIduserType() {
        return this.iduserType;
    }
    
    public void setIduserType(Integer iduserType) {
        this.iduserType = iduserType;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Set getUserRegistrations() {
        return this.userRegistrations;
    }
    
    public void setUserRegistrations(Set userRegistrations) {
        this.userRegistrations = userRegistrations;
    }
    public Set getPrivilageses() {
        return this.privilageses;
    }
    
    public void setPrivilageses(Set privilageses) {
        this.privilageses = privilageses;
    }




}


