package Hibernate;
// Generated Feb 11, 2020 7:58:15 AM by Hibernate Tools 3.6.0



/**
 * UserAddress generated by hbm2java
 */
public class UserAddress  implements java.io.Serializable {


     private int idclientAddress;
     private UserRegistration userRegistration;
     private String country;
     private String province;
     private String postCode;
     private String address;
     private String city;
     private String lane;

    public UserAddress() {
    }

	
    public UserAddress(int idclientAddress, UserRegistration userRegistration) {
        this.idclientAddress = idclientAddress;
        this.userRegistration = userRegistration;
    }
    public UserAddress(int idclientAddress, UserRegistration userRegistration, String country, String province, String postCode, String address, String city, String lane) {
       this.idclientAddress = idclientAddress;
       this.userRegistration = userRegistration;
       this.country = country;
       this.province = province;
       this.postCode = postCode;
       this.address = address;
       this.city = city;
       this.lane = lane;
    }
   
    public int getIdclientAddress() {
        return this.idclientAddress;
    }
    
    public void setIdclientAddress(int idclientAddress) {
        this.idclientAddress = idclientAddress;
    }
    public UserRegistration getUserRegistration() {
        return this.userRegistration;
    }
    
    public void setUserRegistration(UserRegistration userRegistration) {
        this.userRegistration = userRegistration;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getPostCode() {
        return this.postCode;
    }
    
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getLane() {
        return this.lane;
    }
    
    public void setLane(String lane) {
        this.lane = lane;
    }




}


